# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20160324_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followedby',
            old_name='user_name',
            new_name='followed_by',
        ),
        migrations.RenameField(
            model_name='following',
            old_name='user_name',
            new_name='following',
        ),
    ]
